name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        working-directory: ./frontend
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
          browser: chrome

        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

      - name: Generate and check coverage
        working-directory: ./frontend
        run: |
          npx nyc report --reporter=lcov --reporter=text --check-coverage --lines 80 --functions 80 -- branches 80
